steps:
  - block: "Test Benchmark Builds"
    prompt: "Select machines where you want to run a test build"
    fields:
      - select: "Machines"
        key: "machines"
        required: true
        multiple: true
        options:
          - label: "new-amd64-c6a-4xlarge-linux"
            value: "new-amd64-c6a-4xlarge-linux"
          - label: "new-amd64-m5-4xlarge-linux"
            value: "new-amd64-m5-4xlarge-linux"
          - label: "new-arm64-t4g-2xlarge-linux"
            value: "new-arm64-t4g-2xlarge-linux"
          - label: "new-test-mac-arm (Please avoid using this machine for running test builds)"
            value: "new-test-mac-arm"

  - label: "Test Benchmark Builds"
    command: |
      echo "$(buildkite-agent meta-data get machines)"
      docker run -it \
        -e MACHINES="$(buildkite-agent meta-data get machines)" \
        -e BUILDKITE_API_BASE_URL=${BUILDKITE_API_BASE_URL} \
        -e BUILDKITE_ORG=${BUILDKITE_ORG} \
        -e BUILDKITE_API_TOKEN=${BUILDKITE_API_TOKEN} \
        -e BRANCH=${BUILDKITE_BRANCH} \
        -e COMMIT=${BUILDKITE_COMMIT} \
        $(docker build -q .) python -m buildkite.benchmark-test.run_test_builds
    agents:
      # queue: "arrow-bci"
      queue: "aws-855673865593-arm64-t4g-2xlarge"
