steps:
  - label: "Run Benchmarks"
    command: source buildkite/benchmark/utils.sh create_conda_env_and_run_benchmarks
    timeout_in_minutes: $BUILD_TIMEOUT
    retry:
      automatic:
        - exit_status: 255
          limit: 2
