apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrow-bci-deployment
spec:
  selector:
    matchLabels:
      app: arrow-bci
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arrow-bci
    spec:
      containers:
      - name: arrow-bci
        image: "{{DOCKER_REGISTRY}}/{{FLASK_APP}}:{{BUILDKITE_COMMIT}}"
        command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "2", "--threads", "16", "-k", "gthread", "app:app", "--access-logfile=-", "--error-logfile=-", "--timeout", "10", "--keep-alive", "0", "--graceful-timeout", "5"]
        imagePullPolicy: "Always"
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: arrow-bci-config
          - secretRef:
              name: arrow-bci-secrets
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{CERTIFICATE_ARN}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: arrow-bci
  name: "arrow-bci-service"
  namespace: "default"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: "arrow-bci"
